import type {Metadata} from "next";

import "./globals.css";
import localFont from "next/font/local";
import {ReactNode} from "react";

const freeSansFont = localFont({
    src: [
        {
            path: '../../public/fonts/freesans.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/freesansbold.ttf',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-freesans',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${freeSansFont.variable}`}>
        {children}
        </body>
        </html>
    );
}
